version: "2"
services:
# ftp:
#   container_name: ftp
#   image: librairy/ftp:1.0
#   restart: always
#   ports:
#     - "5051:21"
#   volumes:
#     - ./data:/home/ftpusers/librairy
 harvester:
   container_name: harvester
   image: librairy/harvester:latest
   #restart: always
   volumes:
     - ./documents:/librairy/files
   external_links:
     - column-db
     - document-db
     - graph-db
     - event-bus
   networks:
       - "lnet"
networks:
  lnet:
    external:
      name: distribution_lnet
